[project]
name = "resume-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "whenever>=0.8.8",
]

[dependency-groups]
dev = [
    "ruff>=0.12.12",
]
